server:
  port: 8000
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
    min-response-size: 10240

spring:
  application:
    name: diploma-app

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diploma_db
    username: postgres
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        proc:
          param_null_passing: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          batch_versioned_data: true
          lob:
            non_contextual_creation: true

security:
  jwt:
    secret: absolutelySecret
    expire: 900000
